- name: app setup
  include_roles:
    name: common
    tasks_from: app-setup

- name: nodejs setup
  include_roles:
    name: common
    tasks_from: nodejs

- name: systemd setup
  include_roles:
    name: common
    tasks_from: systemd